In [1]:
import tensorflow as tf

In [2]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [6]:
weights = []

for alpha in [.5]:
    x = tf.placeholder(tf.float32, [None, 784])

    W = tf.Variable(tf.zeros([784, 10]))
    b = tf.Variable(tf.zeros([10]))

    y = tf.nn.softmax(tf.matmul(x, W) + b)

    y_ = tf.placeholder(tf.float32, [None, 10])

    cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))

    train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

    init = tf.initialize_all_variables()

    correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))

    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

    sess = tf.Session()
    sess.run(init)

    for i in range(1000):
        batch_xs, batch_ys = mnist.train.next_batch(100)
        sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})


        if i%100 == 0:
            print(sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels}))
            print W.eval(sess)
    #weights.append(W.eval(sess))

0.4322
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
0.8962
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
0.9003
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
0.9113
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
0.9111
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.

In [16]:
print weights[0][14]

[ -1.06755192e-06  -2.92071984e-08   3.39211401e-05  -1.87954896e-07
  -2.40277004e-05  -2.20967440e-08  -5.70709790e-06  -4.84702980e-07
  -1.16136789e-06  -1.23375150e-06]


In [11]:
data_sets = input_data.read_data_sets(FLAGS.train_dir, FLAGS.fake_data)

NameError: name 'FLAGS' is not defined

0.9202


In [2]:
import numpy as np
#Simple network: Given three integers a,b,c, [-100,100] chooses three random x-values, and evaluates
#the quadratic function a*x^2 + b*x + c at those values.
def func(x,a,b,c):
    return x*x*a + x*b + c

def generatecandidate3(a,b,c):


    candidate = [np.random.random() for x in xrange(1)]
    candidatesolutions = [func(x,a,b,c) for x in candidate]
    
    
    return candidate, candidatesolutions

def generatecandidate4(a,b,c,tot):
    
    candidate = [[np.random.random() for x in xrange(1)] for y in xrange(tot)]
    candidatesolutions = [[func(x[0],a,b,c)] for x in candidate]
    
    return (candidate, candidatesolutions)

In [58]:


# Import MINST data
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)

import tensorflow as tf



Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [59]:
# Parameters
learning_rate = 0.1
training_epochs = 15
batch_size = 1000
display_step = 1

# Network Parameters
n_hidden_1 = 4 # 1st layer number of features
n_hidden_2 = 4 # 2nd layer number of features
n_input = 1 # Guess quadratic function
n_classes = 1 # 

# tf Graph input
x = tf.placeholder("float", [None, n_input])
y = tf.placeholder("float", [None, n_classes])

In [317]:
# Create model

class multilayer_perceptron():
    
    #weights = {}
    #biases = {}
    
    def __init__(self, w=0, b=0, ind='00'):
        
        self.index = ind #used for reading values from file
        #See the filesystem convention below (is this really necessary?)
        #I'm going to eschew writing to file for now because I'll be generating too many files
        #Currently, the last value of the parameters is stored in self.params to be read
        
        learning_rate = 0.01
        training_epochs = 15
        batch_size = 1000
        display_step = 1

        # Network Parameters
        n_hidden_1 = 4 # 1st layer number of features
        n_hidden_2 = 4 # 2nd layer number of features
        n_input = 1 # Guess quadratic function
        n_classes = 1 # 
        self.g = tf.Graph()
        
        
        self.params = []
        
        with self.g.as_default():
        
            #Note that by default, weights and biases will be initialized to random normal dists
            if w==0:
                
                self.weights = {
                    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
                    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
                    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
                }
                self.weightslist = [self.weights['h1'],self.weights['h2'],self.weights['out']]
                self.biases = {
                    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
                    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
                    'out': tf.Variable(tf.random_normal([n_classes]))
                }
                self.biaseslist = [self.biases['b1'],self.biases['b2'],self.biases['out']]
                
            else:
                
                self.weights = {
                    'h1': tf.Variable(w[0]),
                    'h2': tf.Variable(w[1]),
                    'out': tf.Variable(w[2])
                }
                self.weightslist = [self.weights['h1'],self.weights['h2'],self.weights['out']]
                self.biases = {
                    'b1': tf.Variable(b[0]),
                    'b2': tf.Variable(b[1]),
                    'out': tf.Variable(b[2])
                }
                self.biaseslist = [self.biases['b1'],self.biases['b2'],self.biases['out']]
            self.saver = tf.train.Saver()
    
    
    def UpdateWeights(self, w, b):
        with self.g.as_default():
            self.weights = {
                    'h1': tf.Variable(w[0]),
                    'h2': tf.Variable(w[1]),
                    'out': tf.Variable(w[2])
                }
            self.weightslist = [self.weights['h1'],self.weights['h2'],self.weights['out']]
            self.biases = {
                'b1': tf.Variable(b[0]),
                'b2': tf.Variable(b[1]),
                'out': tf.Variable(b[2])
            }
            self.biaseslist = [self.biases['b1'],self.biases['b2'],self.biases['out']]
            

        
    def predict(self, x):
        
        with self.g.as_default():
            layer_1 = tf.add(tf.matmul(x, self.weights['h1']), self.biases['b1'])
            layer_1 = tf.nn.relu(layer_1)
            # Hidden layer with RELU activation
            layer_2 = tf.add(tf.matmul(layer_1, self.weights['h2']), self.biases['b2'])
            layer_2 = tf.nn.relu(layer_2)
            # Output layer with linear activation
            out_layer = tf.matmul(layer_2, self.weights['out']) + self.biases['out']
            return out_layer
        
    def ReturnParamsAsList(self):
        
        with self.g.as_default():

            with tf.Session() as sess:
                # Restore variables from disk
                self.saver.restore(sess, "/home/dfreeman/PythonFun/tmp/model"+str(self.index)+".ckpt")                
                return sess.run(self.weightslist), sess.run(self.biaseslist)

        
        
        
        
        

'''def multilayer_perceptron(x, weights, biases):
    # Hidden layer with RELU activation
    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1'])
    layer_1 = tf.nn.relu(layer_1)
    # Hidden layer with RELU activation
    layer_2 = tf.add(tf.matmul(layer_1, weights['h2']), biases['b2'])
    layer_2 = tf.nn.relu(layer_2)
    # Output layer with linear activation
    out_layer = tf.matmul(layer_2, weights['out']) + biases['out']
    return out_layer'''

"def multilayer_perceptron(x, weights, biases):\n    # Hidden layer with RELU activation\n    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1'])\n    layer_1 = tf.nn.relu(layer_1)\n    # Hidden layer with RELU activation\n    layer_2 = tf.add(tf.matmul(layer_1, weights['h2']), biases['b2'])\n    layer_2 = tf.nn.relu(layer_2)\n    # Output layer with linear activation\n    out_layer = tf.matmul(layer_2, weights['out']) + biases['out']\n    return out_layer"

In [53]:
# Store layers weight & bias
weights = {
    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
}
biases = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

# Construct model
test_model = multilayer_perceptron(weights, biases)

pred = test_model.predict(x)

# Define loss and optimizer
#cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(pred, y))
cost = tf.reduce_mean(tf.square(pred-y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# Initializing the variables
init = tf.initialize_all_variables()

In [108]:
xtest, ytest = generatecandidate4(.5,.25,.1,1000)

# Launch the graph
with tf.Session() as sess:
    sess.run(init)

    # Training cycle
    for epoch in range(training_epochs):
        avg_cost = 0.
        total_batch = int(10000/batch_size)
        # Loop over all batches
        for i in range(total_batch):
            batch_x, batch_y = generatecandidate4(.5,.25,.1,batch_size)
            # Run optimization op (backprop) and cost op (to get loss value)
            _, c = sess.run([optimizer, cost], feed_dict={x: batch_x,
                                                          y: batch_y})
            # Compute average loss
            avg_cost += c / total_batch
        # Display logs per epoch step
        if epoch % display_step == 0:
            print "Epoch:", '%04d' % (epoch+1), "cost=", \
                "{:.9f}".format(avg_cost)
    print "Optimization Finished!"

    # Test model
    correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))
    # Calculate accuracy
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    print "Accuracy:", accuracy.eval({x: xtest, y: ytest})

ValueError: Fetch argument <tensorflow.python.framework.ops.Operation object at 0x7fdafd982d10> of <tensorflow.python.framework.ops.Operation object at 0x7fdafd982d10> cannot be interpreted as a Tensor. (Operation name: "init_2"
op: "NoOp"
input: "^Variable/Assign"
input: "^Variable_1/Assign"
input: "^Variable_2/Assign"
input: "^Variable_3/Assign"
input: "^Variable_4/Assign"
input: "^Variable_5/Assign"
 is not an element of this graph.)

In [39]:
x,y = mnist.train.next_batch(2)
print x
print y
x,y = generatecandidate4(.5,.25,.1,2)
print x
print y

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]]
[[0.2913145477141732], [0.7197537451338574]]
[[0.21526071978349995], [0.5389611631005712]]


In [196]:
#xdat,ydat = generatecandidate4(.5, .25, .1, 10)

print xdat, ydat

xdat = np.array(xdat)
ydat = np.array(ydat)

print func(xdat[0][0],.5,.25,.1)


with models[0].g.as_default():

    x = tf.placeholder("float", [None, n_input])
    y = tf.placeholder("float", [None, n_classes])
    pred = models[0].predict(x)

    #cost = tf.reduce_mean(tf.square(pred-y))
    #optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

    # Initializing the variables
    #init = tf.initialize_all_variables()
    #init = tf.initialize_local_variables()
    #init = tf.initialize_variables([x,y])


    
    print "****"
    
    with tf.Session() as sess:
        
        
        #print sess.run(models[0].weights['h1'])
        #sess.run(init)
        models[0].saver.restore(sess, "/home/dfreeman/PythonFun/tmp/model0.ckpt")
            
        print sess.run(models[0].weights['h1'])
        
        
        print "*************"
        #print x.eval()
        correct_prediction = tf.reduce_mean(tf.square(pred-y))
        #correct_prediction = tf.sub(pred,y)
        #print "Diff prediction:"
        #print correct_prediction.eval({x: xdat, y: ydat})
        print "Pred:"
        print pred.eval({x: xdat})
        #print sess.run(pred)
        print "Real:"
        print ydat
        #print sess.run(pred)
        #print sess.run(y)
        # Calculate accuracy
        accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
        print "Accuracy:", accuracy.eval({x: xdat, y: ydat})
        
print models[0].params

[[ 0.6449075 ]
 [ 0.45473615]
 [ 0.33488262]
 [ 0.46034365]
 [ 0.83584571]
 [ 0.89909018]
 [ 0.76755036]
 [ 0.49760915]
 [ 0.90528123]
 [ 0.73978044]] [[ 0.46917971]
 [ 0.31707652]
 [ 0.23979384]
 [ 0.32104405]
 [ 0.65828045]
 [ 0.72895413]
 [ 0.58645437]
 [ 0.34820972]
 [ 0.73608736]
 [ 0.55858266]]
0.469179712727
****
[[ 0.11819226  0.38378665  0.27990231 -1.74266922]]
*************
Pred:
[[ 0.55615944]
 [ 0.3261233 ]
 [ 0.18114549]
 [ 0.33290631]
 [ 0.78712326]
 [ 0.86362571]
 [ 0.70451182]
 [ 0.37798351]
 [ 0.87111408]
 [ 0.67092055]]
Real:
[[ 0.46917971]
 [ 0.31707652]
 [ 0.23979384]
 [ 0.32104405]
 [ 0.65828045]
 [ 0.72895413]
 [ 0.58645437]
 [ 0.34820972]
 [ 0.73608736]
 [ 0.55858266]]
Accuracy: 0.00916406
([array([[ 0.11819226,  0.38378665,  0.27990231, -1.74266922]], dtype=float32), array([[ 0.22078152,  1.18347752,  0.91004926,  0.42721173],
       [ 0.10281421,  0.18740587,  1.87701643, -0.83394569],
       [ 0.63315231,  0.03253949, -0.70630091,  1.60297143],
       [-1.359

In [324]:
import copy

alpha,hidden_dim,hidden_dim2 = (.001,4,4)

thresh = .04

# Parameters
learning_rate = 0.003
training_epochs = 15
batch_size = 2000
display_step = 1

# Network Parameters
n_hidden_1 = 4 # 1st layer number of features
n_hidden_2 = 4 # 2nd layer number of features
n_input = 1 # Guess quadratic function
n_classes = 1 # 
#synapses = []
models = []

#Testing starting in the same place
#synapse0 = 2*np.random.random((1,hidden_dim)) - 1
#synapse1 = 2*np.random.random((hidden_dim,hidden_dim2)) - 1
#synapse2 = 2*np.random.random((hidden_dim2,1)) - 1
copy_model = multilayer_perceptron(ind=0)

for ii in xrange(3):

    '''weights = {
        'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
        'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
        'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
    }
    biases = {
        'b1': tf.Variable(tf.random_normal([n_hidden_1])),
        'b2': tf.Variable(tf.random_normal([n_hidden_2])),
        'out': tf.Variable(tf.random_normal([n_classes]))
    }'''

    # Construct model with different initial weights
    test_model = multilayer_perceptron(ind=ii)
    
    #Construct model with same initial weights
    #test_model = copy.copy(copy_model)
    #test_model.index = ii
    
    
    
    
    #print test_model.weights
    

    
    models.append(test_model)
    with test_model.g.as_default():

        x = tf.placeholder("float", [None, n_input])
        y = tf.placeholder("float", [None, n_classes])
        pred = test_model.predict(x)

        # Define loss and optimizer
        #cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(pred, y))
        cost = tf.reduce_mean(tf.square(pred-y))
        optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

        # Initializing the variables
        init = tf.initialize_all_variables()


        #remove the comment to get random initialization
        stopcond = True




        with tf.Session() as sess:
            sess.run(init)
            xtest, ytest = generatecandidate4(.5,.25,.1,1000)

            while stopcond:
                #print 'epoch:' + str(e)
                #X = []
                #y = []
                j = 0
                # Training cycle
                for epoch in range(training_epochs):
                    avg_cost = 0.
                    total_batch = int(10000/batch_size)

                    if (avg_cost > thresh or avg_cost == 0.) and stopcond:
                    # Loop over all batches
                        for i in range(total_batch):
                            batch_x, batch_y = generatecandidate4(.5,.25,.1,batch_size)
                            # Run optimization op (backprop) and cost op (to get loss value)
                            _, c = sess.run([optimizer, cost], feed_dict={x: batch_x,
                                                                          y: batch_y})
                            # Compute average loss
                            avg_cost += c / total_batch
                        # Display logs per epoch step
                        if epoch % display_step == 0:
                            print "Epoch:", '%04d' % (epoch+1), "cost=", \
                                "{:.9f}".format(avg_cost)

                        if avg_cost < thresh:
                            stopcond = False
                            #test_model.params = sess.run(test_model.weightslist), sess.run(test_model.biaseslist)
                            #save_path = test_model.saver.save(sess,"/home/dfreeman/PythonFun/tmp/model" + str(ii) + ".ckpt")
                            
                print "Optimization Finished!"

                # Test model
                #correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))
                correct_prediction = tf.reduce_mean(tf.square(pred-y))
                # Calculate accuracy
                accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
                print "Accuracy:", accuracy.eval({x: xtest, y: ytest})

                if (j%5000) == 0:
                    print "Error after "+str(j)+" iterations:" + str(accuracy.eval({x: xtest, y: ytest}))

                if accuracy.eval({x: xtest, y: ytest}) < thresh or stopcond == False:
                    #print "Changing stopcond!"
                    stopcond = False
                    print "Final params:"
                    test_model.params = sess.run(test_model.weightslist), sess.run(test_model.biaseslist)
                    save_path = test_model.saver.save(sess,"/home/dfreeman/PythonFun/tmp/model" + str(ii) + ".ckpt")
                j+=1
    #remove the comment to get random initialization

    
    #synapses.append([synapse_0,synapse_1,synapse_2

Epoch: 0001 cost= 1.546539235
Epoch: 0002 cost= 0.726056075
Epoch: 0003 cost= 0.468982208
Epoch: 0004 cost= 0.371891242
Epoch: 0005 cost= 0.338695151
Epoch: 0006 cost= 0.325073898
Epoch: 0007 cost= 0.306272101
Epoch: 0008 cost= 0.304094410
Epoch: 0009 cost= 0.297462350
Epoch: 0010 cost= 0.289633816
Epoch: 0011 cost= 0.285320055
Epoch: 0012 cost= 0.275727344
Epoch: 0013 cost= 0.271105832
Epoch: 0014 cost= 0.265889364
Epoch: 0015 cost= 0.264696819
Optimization Finished!
Accuracy: 0.253653
Error after 0 iterations:0.253653
Epoch: 0001 cost= 0.256881350
Epoch: 0002 cost= 0.252774486
Epoch: 0003 cost= 0.247116360
Epoch: 0004 cost= 0.241427022
Epoch: 0005 cost= 0.239372128
Epoch: 0006 cost= 0.231538355
Epoch: 0007 cost= 0.229884392
Epoch: 0008 cost= 0.225733417
Epoch: 0009 cost= 0.222091913
Epoch: 0010 cost= 0.216191697
Epoch: 0011 cost= 0.215894768
Epoch: 0012 cost= 0.210283139
Epoch: 0013 cost= 0.211168277
Epoch: 0014 cost= 0.201413536
Epoch: 0015 cost= 0.197245428
Optimization Finished!
A

In [73]:
def synapse_interpolate(synapse1, synapse2, t):
    return (synapse2-synapse1)*t + synapse1



'''ii=0
weights = {
'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
}
biases = {
'b1': tf.Variable(tf.random_normal([n_hidden_1])),
'b2': tf.Variable(tf.random_normal([n_hidden_2])),
'out': tf.Variable(tf.random_normal([n_classes]))
}'''

#def model_interpolate(m1, m2, t):
    
    

with models[0].g.as_default():

    with tf.Session() as sess:
        
        # Restore variables from disk.
        
        models[0].saver.restore(sess, "/home/dfreeman/PythonFun/tmp/model0.ckpt")
        modelparams = sess.run(models[0].weightslist[0])
        print sess.run(models[0].weights['h1'])
        print modelparams

        print("Model restored.")
        # Do some work with the model
        
        print models[0].ReturnParamsAsList()[0]
        
        print "**"
        
        print models[1].ReturnParamsAsList()[1]
        
        print "***"
        
        #print models[2].weightslist
        print models[1].params
        print models[1].ReturnParamsAsList()

[[ 0.09790999  0.62101752  1.03343666 -0.38115153]]
[[ 0.09790999  0.62101752  1.03343666 -0.38115153]]
Model restored.
[array([[ 0.09790999,  0.62101752,  1.03343666, -0.38115153]], dtype=float32), array([[ 0.44235808,  0.21506836,  0.761383  ,  0.69092709],
       [-0.03715954,  1.03665876, -0.65453172,  0.45300439],
       [-1.8361553 ,  0.02977604, -0.00432135,  0.1767289 ],
       [-0.53395027,  1.61765206, -0.49521273, -1.70978189]], dtype=float32), array([[ 1.2507863 ],
       [-0.10358144],
       [ 0.16815047],
       [-0.0012698 ]], dtype=float32)]
**
[array([-0.60335797,  0.39746606, -0.38903069,  0.09408516], dtype=float32), array([-0.19858831, -1.76788437,  1.60696042, -2.91697049], dtype=float32), array([-1.86957383], dtype=float32)]
***
([array([[-0.25917089, -2.03158522, -0.12641285, -0.82842195]], dtype=float32), array([[ 0.32461718, -1.12694073,  0.07095902, -0.09691573],
       [-0.1926053 ,  0.11757999, -1.41996026,  0.05515131],
       [-0.11004622,  0.41341448, -0

In [211]:
def synapse_interpolate(synapse1, synapse2, t):
    return (synapse2-synapse1)*t + synapse1

def model_interpolate(w1,b1,w2,b2,t):
    
    m1w = w1
    m1b = b1
    m2w = w2 
    m2b = b2
    
    mwi = [synapse_interpolate(m1we,m2we,t) for m1we, m2we in zip(m1w,m2w)]
    mbi = [synapse_interpolate(m1be,m2be,t) for m1be, m2be in zip(m1b,m2b)]
    
    return mwi, mbi



In [313]:
def synapse_interpolate(synapse1, synapse2, t):
    return (synapse2-synapse1)*t + synapse1




class WeightString:
    
    def __init__(self, w1, b1, w2, b2, numbeads, threshold):
        self.w1 = w1
        self.w2 = w2
        self.b1 = b1
        self.b2 = b2
        #self.w2, self.b2 = m2.params
        self.AllBeads = []

        self.threshold = threshold
        
        self.AllBeads.append([w1,b1])
        
        
        for n in xrange(numbeads):
            ws,bs = model_interpolate(w1,b1,w2,b2, (n + 1.)/(numbeads+1.))
            self.AllBeads.append([ws,bs])
            
        self.AllBeads.append([w2,b2])
        
        
        self.ConvergedList = [False for f in xrange(len(self.AllBeads))]
        self.ConvergedList[0] = True
        self.ConvergedList[-1] = True
    
    
    def SpringNorm(self, order):
        
        total = 0.
        
        #Energy between mobile beads
        for i,b in enumerate(self.AllBeads):
            if i < len(self.AllBeads)-1:
                #print "Tallying energy between bead " + str(i) + " and bead " + str(i+1)
                subtotal = 0.
                for j in xrange(len(b)):
                    subtotal += np.linalg.norm(np.subtract(self.AllBeads[i][0][j],self.AllBeads[i+1][0][j]),ord=order)#/len(self.beads[0][j])
                for j in xrange(len(b)):
                    subtotal += np.linalg.norm(np.subtract(self.AllBeads[i][1][j],self.AllBeads[i+1][1][j]),ord=order)#/len(self.beads[0][j])
                total+=subtotal
        
        return total#/len(self.beads)
        
    
    
    def SGDBead(self, bead, thresh, maxindex):
        
        finalerror = 0.
        
        #thresh = .05

        # Parameters
        learning_rate = 0.01
        training_epochs = 15
        batch_size = 1000
        display_step = 1
        
        curWeights, curBiases = self.AllBeads[bead]
        test_model = multilayer_perceptron(w=curWeights, b=curBiases)

        with test_model.g.as_default():

            x = tf.placeholder("float", [None, n_input])
            y = tf.placeholder("float", [None, n_classes])
            pred = test_model.predict(x)
            cost = tf.reduce_mean(tf.square(pred-y))
            optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)
            init = tf.initialize_all_variables()
            stopcond = True

            with tf.Session() as sess:
                sess.run(init)
                xtest, ytest = generatecandidate4(.5,.25,.1,1000)
                j = 0
                while stopcond:
                    for epoch in range(training_epochs):
                        avg_cost = 0.
                        total_batch = int(10000/batch_size)
                        if (avg_cost > thresh or avg_cost == 0.) and stopcond:
                        # Loop over all batches
                            for i in range(total_batch):
                                batch_x, batch_y = generatecandidate4(.5,.25,.1,batch_size)
                                # Run optimization op (backprop) and cost op (to get loss value)
                                _, c = sess.run([optimizer, cost], feed_dict={x: batch_x,
                                                                              y: batch_y})
                                # Compute average loss
                                avg_cost += c / total_batch
                            # Display logs per epoch step
                            #if epoch % display_step == 0:
                            #    print "Epoch:", '%04d' % (epoch+1), "cost=", \
                            #        "{:.9f}".format(avg_cost)

                            if avg_cost < thresh:
                                stopcond = False
                    #print "Optimization Finished!"

                    # Test model
                    #correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))
                    correct_prediction = tf.reduce_mean(tf.square(pred-y))
                    # Calculate accuracy
                    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
                    print "Accuracy:", accuracy.eval({x: xtest, y: ytest})

                    #if (j%5000) == 0:
                    #    print "Error after "+str(j)+" iterations:" + str(accuracy.eval({x: xtest, y: ytest}))

                    finalerror = accuracy.eval({x: xtest, y: ytest})
                    
                    if finalerror < thresh or stopcond==False:# or j > maxindex:
                        #print "Changing stopcond!"
                        stopcond = False
                        #print "Final params:"
                        test_model.params = sess.run(test_model.weightslist), sess.run(test_model.biaseslist)
                        self.AllBeads[bead]=test_model.params
                        print "Final bead error: " + str(finalerror)
                        
                    j+=1

            return finalerror




In [240]:
i1=0
i2=1
test = WeightString(models[i1].params[0],models[i1].params[1],models[i2].params[0],models[i2].params[1],1,1)
print len(test.AllBeads)
print test.SGDBead(1,.01,10)

3
0.00979065


In [314]:
def InterpBeadError(w1,b1, w2,b2, write = False, name = "00"):
    errors = []
    
    xdat,ydat = generatecandidate4(.5, .25, .1, 1000)
    xdat = np.array(xdat)
    ydat = np.array(ydat)
    
    
    
    
    for tt in xrange(100):
        #print tt
        #accuracy = 0.
        t = tt/100.
        thiserror = 0

        #x0 = tf.placeholder("float", [None, n_input])
        #y0 = tf.placeholder("float", [None, n_classes])
        weights, biases = model_interpolate(w1,b1,w2,b2, t)
        interp_model = multilayer_perceptron(w=weights, b=biases)
        
        with interp_model.g.as_default():
            
            #interp_model.UpdateWeights(weights, biases)


            x = tf.placeholder("float", [None, n_input])
            y = tf.placeholder("float", [None, n_classes])
            pred = interp_model.predict(x)
            init = tf.initialize_all_variables()


            with tf.Session() as sess:
                sess.run(init)
                correct_prediction = tf.reduce_mean(tf.square(pred-y))
                accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
                print "Accuracy:", accuracy.eval({x: xdat, y: ydat}),"\t",tt
                thiserror = accuracy.eval({x: xdat, y: ydat})


        errors.append(thiserror)

    if write == True:
        with open("f" + str(name) + ".out",'w+') as f:
            for e in errors:
                f.write(str(e) + "\n")
    
    return max(errors), np.argmax(errors)

In [227]:
InterpBeadError(models[0].params[0],models[0].params[1],models[1].params[0],models[1].params[1])

0.25772259

In [330]:

#Used for softening the training criteria.  There's some fuzz required due to the difference in 
#training error between test and training
thresh_multiplier = 1.1

    
results = []

connecteddict = {}
for i1 in xrange(len(models)):
    connecteddict[i1] = 'not connected'


for i1 in xrange(len(models)):
    print i1
    for i2 in xrange(len(models)):
        
        if i2 > i1 and ((connecteddict[i1] != connecteddict[i2]) or (connecteddict[i1] == 'not connected' or connecteddict[i2] == 'not connected')) :
            #print "slow1?"
            #print i1,i2
            #print models[0]
            #print models[1]
            #print models[0].params
            #print models[1].params
            test = WeightString(models[i1].params[0],models[i1].params[1],models[i2].params[0],models[i2].params[1],1,1)

            training_threshold = thresh

            depth = 0
            d_max = 10

            #Check error between beads
            #Alg: for each bead at depth i, SGD until converged.
            #For beads with max error along path too large, add another bead between them, repeat

            
            #Keeps track of which indices to check the interpbeaderror between
            newindices = [0,1]
            
            while (depth < d_max):
                print newindices
                #print "slow2?"
                #X, y = GenTest(X,y)
                counter = 0

                for i,c in enumerate(test.ConvergedList):
                    if c == False:
                        #print "slow3?"
                        error = test.SGDBead(i, .5*training_threshold, 20)
                        #print "slow4?"
                            #if counter%5000==0:
                            #    print counter
                            #    print error
                        test.ConvergedList[i] = True

                print test.ConvergedList

                interperrors = []
                interp_bead_indices = []
                for b in xrange(len(test.AllBeads)-1):
                    if b in newindices:
                        e = InterpBeadError(test.AllBeads[b][0],test.AllBeads[b][1], test.AllBeads[b+1][0], test.AllBeads[b+1][1])

                        interperrors.append(e)
                        interp_bead_indices.append(b)
                print interperrors

                if max([ee[0] for ee in interperrors]) < thresh_multiplier*training_threshold:
                    depth = 2*d_max
                    #print test.ConvergedList
                    #print test.SpringNorm(2)
                    #print "Done!"

                else:
                    del newindices[:]
                    #Interperrors stores the maximum error on the path between beads
                    #shift index to account for added beads
                    shift = 0
                    for i, ie in enumerate(interperrors):
                        if ie[0] > thresh_multiplier*training_threshold:
                            k = interp_bead_indices[i]
                            
                            ws,bs = model_interpolate(test.AllBeads[k+shift][0],test.AllBeads[k+shift][1],\
                                                      test.AllBeads[k+shift+1][0],test.AllBeads[k+shift+1][1],\
                                                      ie[1]/100.)
                            
                            test.AllBeads.insert(k+shift+1,[ws,bs])
                            test.ConvergedList.insert(k+shift+1, False)
                            newindices.append(k+shift+1)
                            newindices.append(k+shift)
                            shift+=1
                            #print test.ConvergedList
                            #print test.SpringNorm(2)


                    #print d_max
                    depth += 1
            if depth == 2*d_max:
                results.append([i1,i2,test.SpringNorm(2),"Connected"])
                if connecteddict[i1] == 'not connected' and connecteddict[i2] == 'not connected':
                    connecteddict[i1] = i1
                    connecteddict[i2] = i1

                if connecteddict[i1] == 'not connected':
                    connecteddict[i1] = connecteddict[i2]
                else:
                    if connecteddict[i2] == 'not connected':
                        connecteddict[i2] = connecteddict[i1]
                    else:
                        if connecteddict[i1] != 'not connected' and connecteddict[i2] != 'not connected':
                            hold = connecteddict[i2]
                            connecteddict[i2] = connecteddict[i1]
                            for h in xrange(len(models)):
                                if connecteddict[h] == hold:
                                    connecteddict[h] = connecteddict[i1]
                    
            else:
                results.append([i1,i2,test.SpringNorm(2),"Disconnected"])
            #print results[-1]
	
	
	

uniquecomps = []
totalcomps = 0
for i in xrange(len(models)):
    if not (connecteddict[i] in uniquecomps):
        uniquecomps.append(connecteddict[i])
    
    if connecteddict[i] == 'not connected':
        totalcomps += 1
        
    #print i,connecteddict[i]

notconoffset = 0

if 'not connected' in uniquecomps:
    notconoffset = -1
    
print "Thresh: " + str(thresh)
print "Comps: " + str(len(uniquecomps) + notconoffset + totalcomps)



#for i in xrange(len(synapses)):
#    print connecteddict[i]

connsum = []
for r in results:
    if r[3] == "Connected":
        connsum.append(r[2])
        #print r[2]
        
print "***"
print np.average(connsum)
print np.std(connsum)

0
[0, 1]
Accuracy: 0.0277865
Accuracy: 0.0182306
Final bead error: 0.0182306
[True, True, True]
Accuracy: 0.0423283 	0
Accuracy: 0.0424689 	1
Accuracy: 0.0426616 	2
Accuracy: 0.0429018 	3
Accuracy: 0.0431851 	4
Accuracy: 0.043507 	5
Accuracy: 0.0438634 	6
Accuracy: 0.0442503 	7
Accuracy: 0.0446639 	8
Accuracy: 0.0451004 	9
Accuracy: 0.0455565 	10
Accuracy: 0.0460287 	11
Accuracy: 0.0465137 	12
Accuracy: 0.0470087 	13
Accuracy: 0.0475105 	14
Accuracy: 0.0480166 	15
Accuracy: 0.0485243 	16
Accuracy: 0.049031 	17
Accuracy: 0.0495345 	18
Accuracy: 0.0500325 	19
Accuracy: 0.050523 	20
Accuracy: 0.051004 	21
Accuracy: 0.0514738 	22
Accuracy: 0.0519305 	23
Accuracy: 0.0523728 	24
Accuracy: 0.052799 	25
Accuracy: 0.053208 	26
Accuracy: 0.0535984 	27
Accuracy: 0.0539519 	28
Accuracy: 0.05426 	29
Accuracy: 0.0545226 	30
Accuracy: 0.0547568 	31
Accuracy: 0.0549814 	32
Accuracy: 0.0551839 	33
Accuracy: 0.0553951 	34
Accuracy: 0.0555975 	35
Accuracy: 0.0557932 	36
Accuracy: 0.0559965 	37
Accuracy: 

In [258]:
print len(models)

3


In [261]:
connecteddict[2]

'not connected'

In [293]:
models[0].params

([array([[-1.4998107 , -0.23091862,  0.1918727 ,  0.20560187]], dtype=float32),
  array([[-1.17867899,  0.78579026, -0.89930582, -1.24247086],
         [-0.86114722, -0.1602481 , -0.86737674, -1.13779354],
         [ 0.72442532, -0.57136399,  0.78054297, -0.60431153],
         [-0.08741271, -0.26723036,  0.54410225,  0.19356832]], dtype=float32),
  array([[ 0.61557311],
         [ 0.35026345],
         [ 0.14537683],
         [-0.67227656]], dtype=float32)],
 [array([-0.07781173,  0.05719442, -2.12461662, -1.48168921], dtype=float32),
  array([-1.76856709, -0.59562606,  3.31021976, -1.39359915], dtype=float32),
  array([-0.24812987], dtype=float32)])

In [294]:
models[1].params

([array([[-1.00434339,  0.85087883, -0.4409067 , -0.07457321]], dtype=float32),
  array([[ 0.75883377, -0.20007004,  0.41354284,  0.29582518],
         [ 0.00292377,  1.28025246,  0.57766509,  1.37554467],
         [-1.0842402 ,  1.0441618 , -0.43416622,  0.22762316],
         [-2.10338879, -1.36171842, -0.22631967,  0.58631068]], dtype=float32),
  array([[-0.11565071],
         [ 0.33658049],
         [-1.14827919],
         [ 0.68962663]], dtype=float32)],
 [array([ 0.73745489, -0.77259034, -1.86909771,  1.6973933 ], dtype=float32),
  array([ 1.3530215 , -1.10458112,  0.21234779, -1.07358325], dtype=float32),
  array([ 0.20686743], dtype=float32)])

In [331]:
len(test.AllBeads)

13

In [335]:
#for b in xrange(len(test.AllBeads)-1):
#    e = InterpBeadError(test.AllBeads[b][0],test.AllBeads[b][1], test.AllBeads[b+1][0], test.AllBeads[b+1][1])
#for b in xrange(len(test.AllBeads)):
#    print test.AllBeads[b][0]

xdat,ydat = generatecandidate4(.5, .25, .1, 1000)
xdat = np.array(xdat)
ydat = np.array(ydat)

def InterpBeadError_SameSet(w1,b1, w2,b2,xdat, ydat, write = False, name = "00"):
    errors = []
    

    
    
    
    
    for tt in xrange(100):
        #print tt
        #accuracy = 0.
        t = tt/100.
        thiserror = 0

        #x0 = tf.placeholder("float", [None, n_input])
        #y0 = tf.placeholder("float", [None, n_classes])
        weights, biases = model_interpolate(w1,b1,w2,b2, t)
        interp_model = multilayer_perceptron(w=weights, b=biases)
        
        with interp_model.g.as_default():
            
            #interp_model.UpdateWeights(weights, biases)


            x = tf.placeholder("float", [None, n_input])
            y = tf.placeholder("float", [None, n_classes])
            pred = interp_model.predict(x)
            init = tf.initialize_all_variables()


            with tf.Session() as sess:
                sess.run(init)
                correct_prediction = tf.reduce_mean(tf.square(pred-y))
                accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
                print "Accuracy:", accuracy.eval({x: xdat, y: ydat}),"\t",tt
                thiserror = accuracy.eval({x: xdat, y: ydat})


        errors.append(thiserror)

    if write == True:
        with open("f" + str(name) + ".out",'w+') as f:
            for e in errors:
                f.write(str(e) + "\n")
    
    return max(errors), np.argmax(errors)


for b in xrange(len(test.AllBeads)-1):
    e = InterpBeadError_SameSet(test.AllBeads[b][0],test.AllBeads[b][1], test.AllBeads[b+1][0], test.AllBeads[b+1][1], xdat, ydat)

Accuracy: 0.0417373 	0
Accuracy: 0.0417649 	1
Accuracy: 0.0417958 	2
Accuracy: 0.0418295 	3
Accuracy: 0.0418655 	4
Accuracy: 0.0419032 	5
Accuracy: 0.0419423 	6
Accuracy: 0.0419823 	7
Accuracy: 0.0420228 	8
Accuracy: 0.0420632 	9
Accuracy: 0.0421033 	10
Accuracy: 0.0421425 	11
Accuracy: 0.0421806 	12
Accuracy: 0.042217 	13
Accuracy: 0.0422514 	14
Accuracy: 0.0422835 	15
Accuracy: 0.0423129 	16
Accuracy: 0.0423392 	17
Accuracy: 0.0423621 	18
Accuracy: 0.0423813 	19
Accuracy: 0.0423964 	20
Accuracy: 0.0424072 	21
Accuracy: 0.0424134 	22
Accuracy: 0.0424146 	23
Accuracy: 0.0424107 	24
Accuracy: 0.0424014 	25
Accuracy: 0.0423864 	26
Accuracy: 0.0423654 	27
Accuracy: 0.0423383 	28
Accuracy: 0.0423049 	29
Accuracy: 0.0422649 	30
Accuracy: 0.0422182 	31
Accuracy: 0.0421646 	32
Accuracy: 0.042104 	33
Accuracy: 0.0420361 	34
Accuracy: 0.0419609 	35
Accuracy: 0.0418782 	36
Accuracy: 0.0417879 	37
Accuracy: 0.0416899 	38
Accuracy: 0.0415841 	39
Accuracy: 0.0414705 	40
Accuracy: 0.041349 	41
Accur